### PR TITLE
Update librespot to 0.4.2

### PR DESCRIPTION
**Pull request by basveeling**
# Proposed Changes

Update version number of 0.4.2

Note: I was not able to test this change yet, based this on #174 

## Related Issues

#182 
https://github.com/librespot-org/librespot/issues/972

### CODE REVIEW

**Comment by frenck** [comment]
> Note: I was not able to test this change yet, based this on https://github.com/hassio-addons/addon-spotify-connect/pull/174

So, what do you expect me to do with it? Why do you open untested PRs?
Don't get me wrong, I appreciate the effort, but merging untested PRs sounds like a thing I should never ever do.

../Frenck

**Comment by basveeling** [comment]
Hi Frenck,

Thanks for the speedy reply! Fully understand that for a busy maintainer, an untested PR is sometimes worse than no PR :). Given that this add-on is currently broken due to an issue at Spotify's end of things, I figured a quick stab at a fix might be better than waiting for someone to have the chance to fully test things through. I don't have the facilities to test this PR myself, happy to close it if you prefer.

**Comment by Wumpf** [comment]
Apologies for (sort of) hijacking this thread here, but maybe can someone can point out in this context where I'm going wrong on how to test the addon modification? :)

I'm new to docker and HA add-ons, so I've been struggling with this quite a bit:
Managed to run it on a local HA assistant but the addon seems to crash on start, last log message is a warning, `mdns: Failed to register IPv6 receiver`, but seems unlikely to be the culprit. Given that I also couldn't set any of the config options I suspect my setup was somewhat shaky.
Next I tried adding the modified add-on to my RPI, looked promising at first but building on there takes way too long. So I eventually figured out how to build for aarch64 locally as well, ending up with a docker image. But now I can't find any documentation on how to run the local addon with the prebuilt image (tried uploading to docker hub and reference it with the `image` tag in config.yml, but didn't figure out how to set it correctly). Followed mostly the manual page on [addon testing](https://developers.home-assistant.io/docs/add-ons/testing).

**Comment by frenck** [comment]
> Fully understand that for a busy maintainer, an untested PR is sometimes worse than no PR :).

Sorry, I really do not agree. It requires me to divert my attention to untested things. Time and attention I could have used elsewhere.

**Comment by basveeling** [comment]
This change has now been successfully tested by @KNXBroker 
See: 
https://github.com/hassio-addons/addon-spotify-connect/issues/182#issuecomment-1200478129

**Comment by basveeling** [comment]
@frenck Is there anything else you need from this PR before it can be merged?

**Pull request closed without merging**
