### PR TITLE
WIP: Add functionality to trigger HA events

### PR DESCRIPTION
**Pull request by Alwinator**
# Proposed Changes
Speakers usually consume a lot of energy. So, I plugged my speakers into a smart plug and turned them on or off based on the source of my Spotify account.

However, this only works for my Spotify and has a delay of around 20 seconds.

So, I had the idea to integrate Spotify-connect more into HA. Based on the logs it will trigger events for new connections, new songs, and other events.

In this way, you can build automations based on Spotify-connect.

**I am not done yet**, but I still wanted to create a PR, so you can maybe guide me in which direction this should go. However, the basic functionality is implemented.

### CODE REVIEW

**Comment by frenck** [comment]
>So, I had the idea to integrate Spotify-connect more into HA.

That is not an add-on responsibility, that is a responsibility of an add-on. It sounds like you are building something in the wrong place?

../Frenck

**Comment by Alwinator** [comment]
@frenck Thanks! :)

> That is not an add-on responsibility, that is a responsibility of an add-on

I am not sure if I understand what you want to say. Do you mean instead of integrating it into your add-on I should build a separate add-on that fetches you logs?

> It sounds like you are building something in the wrong place?

Which place would you as an expert recommend, when I want to build my kind of automation?

**Comment by Alwinator** [comment]
@frenck :)

**Comment by frenck** [comment]
Sorry missed your response.

This is not an integration. Integrations integrate with Home Assistant. Add-ons provides services; services integrations could integrate with.

This PR isn't valid and in the wrong location. If you want to integrate things with Home Assistant, please build integrations.

../Frenck

**Pull request closed without merging**
